hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

ports:
  web:
    expose:
      default: false
  websecure:
    expose:
      default: true
  metrics:
    port: 9101

securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
    drop:
      - ALL
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

additionalArguments:
  - "--entrypoints.wss-internal.address=100.105.6.9:443"
  - "--entrypoints.wss-public.address=127.0.0.1:8444"

service:
  enabled: true
  type: ClusterIP

ingressRoute:
  dashboard:
    enabled: false

metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
