apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:jE8DpOUXZ6CGOgZDyhf/7seKMGWgYkudtkSwW/Tj/NJCE2cVDIaefzbeGmsTZnUPNrckZtM=,iv:ycYuX2Svp+GLP0v/ZomhNj6757C+hnnvAmEojGqgL/A=,tag:5OE3BZ6Pml4UTd0WBQFDrQ==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWXdmMEdodW5RODRtRFhq
            ZUJueHh4QzMvdVJMS2FHQjVKVWoyRkUxUGxRClpHVXVpT0VSQ0RvVGwzd1cxWlR2
            VmNHR3B3STdDa0F5WkpVZTFvS0tYc2cKLS0tIDdhV2FwWVlMeW1sRTBCV1NMdEZ1
            Z0ltaFhGQSsxV0NmRmMydm9iOUp4VWcKNLkwoPNed6GxisY5wDrOg2Sr5b6o+j2Z
            gMjdpH5A9jOgIOD/GmlJSqD8INkWXBdUH5NUp2ymkvrSEXgpvAvGjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T16:34:45Z"
    mac: ENC[AES256_GCM,data:6jkUr+c0T/AEcFT7PLSiUolR4qsajb7/rNs404ye69XJdOczgawfzGao27gI/Cb9CJYcBM2duXwBrFNAaNte2/fhMuNrJWK7rpAYCaGG12SUhDr3E4zOFUS8qnoyOdA6dBel3lPXg3xs3Zuk7zC7OycGEtWReZpn9/jESYAKUHg=,iv:aIsI7lzHD62LbvKnPHQ7iTPAZfmIwVZKz52H6PkZxVY=,tag:YD2er+OWSWvjwiwJ2/8yag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
