apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: cert-manager
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ohqDS2VAOaad3EJUIKkwYRE+ZoY=,iv:WkYmhhZH4QJZTpdbRryCE1Yq5Vwp+u41nR942c9F4yU=,tag:tNn15VAChiXsvJ15FtLrBw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HQbtSVr/sp/xTv3w5wawzjuSLr6xK0t3QL7g6TKDBtua4XTlvs1XsA==,iv:iLWGw+cO9sqShaQf89bWgQNEPQTWTzV0AQQztQLzwAU=,tag:wosOpQwkelIW3Z/3FDngjg==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxclJzOUM1dVJvejh0ZTI4
            NUc1MlE4YWErS0dKRytTNzR0U05ueW5oZDJRClBYeE5uRnF5ZXB4QmtjdkdUeWo0
            S2xIUEc0K2E0TDNXcHRTcHBVeDBIZXMKLS0tIHV1Wmwva1NRMmFJNUk5Y2RILzZL
            SXNKUEQ2N3R6WGtPU1ZRclZvMmJxUEEK6yMAbxf5kcphrPVN4K0VmGTsQC2kv2WC
            DR3fI/QhvZc/ssQh6U3c7FYnNzG0EJRAL8kzrusjf5refzBEDOiyNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:52:22Z"
    mac: ENC[AES256_GCM,data:LMCtA9wl8lQvwyUZdFg9htKqvoDWhbtyY3HAbpFgGXtz4+F3wWxwTqJftGsllqhIgW9tYBfzrw8ElOBDotlT8C2aFppx6q5vGupzEEyTW+rta8pyeIwYQjULOdpzOqEII+efpYJJ4++7gnSaz4nMv3b3PrUOLFdYoaPykR48xYw=,iv:7yTlp/d3cTK5/5f/zknS4sjJrjoVr0D6jnm+QpYgBS8=,tag:6v8cXFZ62pAv9PSk/77+hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
