apiVersion: v1
kind: Secret
metadata:
    name: testdb-superuser
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rdAJ8RMHJlg=,iv:103RiYL0CqvSCiLur6+M/WShwzbJXvuiE8oXkudTT2I=,tag:QwwnkJoGXWnTLz+0d5rH5A==,type:str]
    password: ENC[AES256_GCM,data:ksf1DkhiIdwsh+zaNLIG9rpFNXMgkOoWgz9M,iv:m2R576lyjrLrUW8mOl94GzdQCwksjb9RPNCzaCFyCHE=,tag:qOlRd69Y0kUIVWEIe07Vww==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZkdhR2h0am4rQ0NpdFBp
            d2x3aUl6dU5KVTJhTDhGL08zMWh1WENLdFRjCnVMTEJLc2lGZFFtTEdRVEtrVVlt
            TG5tQUl6NTNNM0lua2p0ZGQzZUdobkkKLS0tIDlJM1ZjRXI3QloyYXAvZDhkNVR2
            eis2bzFacVUyeDAyK1BtWWJjT3VSVDgK0ltBSz/e3dhJIV89gWjNtyKes841EGIT
            yKrLRygZQ1Ga5RUHnudpDJGQiC+zl7LyL8a3AmJrpxv8uhH3uOnDkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:31:24Z"
    mac: ENC[AES256_GCM,data:vCos07+KiZGhIF/58undQpGtC3WFQfXtnvqIm4xUVMY9weDCzfwaDJsPpRWXXGl4aWoJh3HmeTVcdZu4j6yWEr1k4HA7IPpxpb4xuHgu0lRbVolerphE7TslsUDe0ieexYEv0f4q5h8aViV4UZFfBD8kClaXahDJnNiYxK+nF1Q=,iv:CcAwpP1Ua4xs6hOe+SLgzApZgvTCEqPurb1K97QqtA4=,tag:Ho1T9508F4QzOsit+RZ+Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
