apiVersion: v1
kind: Secret
metadata:
    name: testdb-superuser
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ZHtvqwyb,iv:eCWIjyF+F2k1dFrRJPyNNAvZL2zjGaozU6RZGjqQ0EQ=,tag:bHmIW4LLw7VKlJNNziLakg==,type:str]
    password: ENC[AES256_GCM,data:tNYFUOaLfmxS0Sk04irquj2rWDdvmrWSJtfH,iv:epmBQAl9jeQIE0/1ADbQgb0wgUAYYN0MWOTMYAQzCus=,tag:cgkyoz4uXRYaqtQ/xTADzw==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkdhTjlJTHVxWW9LeHAy
            bkozaEFYQ3JDS292T1N6aHBpWU9IVUZtam5VCnVaT01yQ1dGM08xWkc2bVhZZnIz
            R2NuRm4wMHZMV2JpTVZaWlVZc3owL1EKLS0tIHZwbGo2TkwzVGFPbUhmeUZSeE83
            dzZKc0x3YkZvMkhPUlN6ME9weXZmQVkKOreuC1t0Ha05h0n6mdw4Zg3K061/NPiM
            +EzSvWy8i0KQ23APQY15t1pBvIBSTZipAlLbsvhudCxyA1nStgPTgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:58:29Z"
    mac: ENC[AES256_GCM,data:MO3R2VobjOxgrHPOwnPiYilA3fP+oW61JlUXF7kNOs7Mjy7qxor45RexFpg4v5Pb6hjMamK9tuCpJQIAjFi6eDCTlbCMTaqQMF0j/TY9s+JZhv5pjBe+wGlsu8lq4KmienClUH531PJB5eVWUSiOgGR00gO1jt7z6Lr8ngpQ53A=,iv:WMaKBrhr4JV7nZEcIebIvGd/CnTESv+XbNKvpInH0+s=,tag:ss5wo3aZEPTRmRpji4aVRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
