apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-tls
  namespace: apps
spec:
  secretName: blog-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - blog.thehutchery.com
