apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: apps
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:loDSBicO3+3IM8L3hWSs+KZ2FC66czn75odlOS78+KFex572Poc0Fu6F6xMQw3u9cbUvj824mMHjd1M5uVFmBbI2wGlG5es6vvMnI6s9SDcVXUneltDpcrHx6V49rvT0xk9dtwWz+1En,iv:/OxR9/UFuKCdS2ra1T5lIPNVObDiOC11g5CQ4Lztw+E=,tag:CJ/HqU80fCbJhO0oBzs5yA==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYlVYZmdudHVOM1pKanN2
            YjNRL0hXUk1XdmE0ZmllY0RINE9aZ09nczFJCmFaL0hKc3dXalBCTFhoS3RmNmkv
            ZG1rTllFbVJ2NTRsUmpKdTllVFJWVHcKLS0tIEg3MzVzQTkyUTdIc2tSSU1MeVN6
            aUVoOUdFaFMzRE9ybUlDRWdaUkpqcFUK9dtSVuExXHbAg9dDUlFQk/V0wUQHvgMA
            Gwj8osfd26eZxAdd1ZtIrOle/SXEKQg39RB80afydIpUGU9vRQ5sug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:21:10Z"
    mac: ENC[AES256_GCM,data:qMOYdpVqFI7xNvzARK56svg4qFpb5qhX7YtsnxmFFY9HN7UxVKdFVjxeJj0FNfrMyC9Gb/HOJGZ2LU8vq63YUS5XW2fVYrUyP0LcIwovHPCkP6ANsK9k3Bt+3K3ORzOCLMxu7cxWKM2Uj9yjkTT8Z1Ozp0f7e/4UOciH29nRnsw=,iv:4ZHRSqa6sIl1cmfKpK321Ao/z76dgHJPNGjj/dEWmJ4=,tag:P1mK40DZaqD2TZhFvhZqmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
