apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog
  namespace: apps
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    pattern: "^[0-9a-f]{7}$"
  policy:
    alphabetical:
      order: asc
