apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: apps
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:NNHLh0ZpPDBGVhMTspMUtkQXme3ZyZnvOeSa/+uM1z1lJsQiiovdCnB9j2xb+11efi3eN4DA9G7Wo/QUZEjWcEfWjYsmVReeN2cT1VRsR8q1kTxvVxbIjrfTh7Cyy5s7uMnfz5lS82Cw,iv:zIVla0uVBYCW5uurdgcFyCvYbebcmpptcMK0532CWQk=,tag:9acXuDG8FO7ZvPNML+8/MQ==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVXpQS2toRHZsaEFCcXF2
            UWlXaHBzM2NDNnVHUUl3aWxYb0JMZ2VPbWlvCjREcXZCbW1PWEtHa0FHS1NFaEd1
            Y2JMSHVnZDF1c3pHUzM1ay9RSFJrV28KLS0tIDB0bFBlaFd6UjRadit2anF4ZUZI
            WlM0a2pZUU5qU3g2cXZQazBvNGE3RHMKSMLUIWXmH9CAbW/P9rRRUqMi/EBWxfVW
            331wlQ+VJg8kVYitWzc6ruqOzxE9ftMLjAG3uUrgiDgOFFIPW8ZIBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:50:36Z"
    mac: ENC[AES256_GCM,data:gSBuy3x35ygBlegGQ1cnrBudzUEGwoGtC5WqiCViNnSz22XXHVJ19ZrgSMCcjGvCpF4ANJ1IKywzzoe3x9Wm8Zr6IZAX6vbDi9flFjf2KVrzvbUk0HPC8fhxA+BD2PpDd+AP3YcR0wAm19qzle4FKcihagrmhtHTsi/OUhkaA70=,iv:R3xxitg33zcSpUA8iMTHfrA8n++D+7trHCbr/0xAVTA=,tag:Nv5ELpggr5ZPAVa4G0ywKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
