apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:+xsLUIV5xdOjPRkKq316cdY8be2mGb4mGf2Zo2nxJfuG5ELePQ==,iv:QTw7t6ZcWoFEoISyKNb6Z9TrK5Blia2ejdahHSCqub4=,tag:SzE1fT//RcABWcfXNRD2BQ==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NzIxYnI5ZzVJU3BZVFhx
            anZ0NGpSeHBBTm50WFpXUS94NlVXR1dGV2hVClBsS1NDUDlDaGg5Q24rUGVwdFRB
            eENFbUN3d2xmSW56anQvQkpXeXpSd2cKLS0tIExtVStnbDVXaldabUhOdDJtVllF
            OFZGeisreTRzbTR1NXYyUk5EdlFuSUUKaZnVzZtt64Oz78Iqy9TjnAgJh7XiBu/y
            F5Z6BZuWHgnv2u/vdRnPsa3s6BfPdEAC6Jt7OvEON42u4roP0khBqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:56:39Z"
    mac: ENC[AES256_GCM,data:7D5qCToitnw0YZcQx88zTXmIjf+cFDQIed34HnOTSKoA8RJNa09ZWvXDGAcbl1t0nGgfNlxKDIA68bpofCC3fXluooHrPfJwhtEiBuYHchJdgGw5Afw6DoJksUiwTzdQAf3ETAI6I7fPymMz2ISglfhaN//JxhCjVagjpJtWnVc=,iv:RKP2qoQpm27ID4BCOvxbgs+mB7Q0nT/gx/rvue+hqrE=,tag:OqwJyPs2DvOC1YOwG6J3eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
