apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:WKzlnzW45ORsfiXDBouvO4J67Fv/40pP6zHnZyMQp/XCLQFvFg==,iv:vs8DJk9/krxpM7RipAZfJ0eRzpMeu7bZdaP4d1u6e2Q=,tag:hElc9eGJsTUWxFpLnZwhSw==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVU9YclBja1pRMFNlcFps
            WVlQMVhqM015SkxqRnkxY0hzT0JJbDFzTWdjCi81UDlzTDF0RjdQdGhCQWdYMHBU
            ZnVqalNBUEUzd2QvaXAycUhnMHdiNmcKLS0tIFNwemRVbUg3V0o2OTRHeVRGNllG
            T3ZuUmRBblJSODN4ZTBsemlnTzZ6SXMKfzSZb+jeIYyGJmY2x1JgbHZ1sZEAXhHE
            W6GoIheBxS9f//v3s80OmbXhT91B40Fgnu2A56TWtp4ll9sHcCXNAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T14:48:37Z"
    mac: ENC[AES256_GCM,data:iyQSwrgxki/nt/6LLMpFpnpFjCyMRCw9QGtFcxUcd1ARdfWkUTlhIPyIidFbE8a/9pIwe7VHAQlk+1ZooEYTbOvz8GL8wCrMLqwknOBSwQMlK6zmCOOeUMgNt7aNHX827MaQk00J1G/W8A0okvg4xS1P6na8ohIkOqpyE4tUAak=,iv:WqTs6TyXdwRRKMuGd+/VaL9kI3y6LHgS6rAFhzZBHNg=,tag:RFugZKoI4+WL6i2g7vEcpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
