grafana:
  enabled: true
  ingress:
    enabled: false
  adminUser: admin
  adminPassword: "" # Overridden by SOPS secret
  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
