apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: routing
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:HC5OG31Ze4I+AY1yfH5ycW3iBVdO5RlxC3hWEcGcMdChpETm687W9qSWQK7Yv0v6lktCz/g8qFbNYO+QyBZrWr2njIw6qocsMZ8RQjrbt4T69dtxrGlX2SjifuIiqAAeArZnNjuHoda2tqpqXXv4mql0y71tW3DtruA/HLu2bEb6on1MMAUPVAt3a0N9JoBAGkOat1iXf7NB9sLrGsKhHkCL/8f8bo1MiN34IfoFK3jNThAajcpJZQ==,iv:2kOkTMsjTnd4jaPktgy3gAmbgWsN19W6WCj8Ygiq8U0=,tag:TfOy4HRclK5bVt5mvJIkew==,type:str]
sops:
    age:
        - recipient: age1xktzf37vtkpcs8zzlpx4qluw5p5d4dyw5jh4zq53vhhjn9p3re8sekav9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMVNwSEZENDBZOURPZFlZ
            eEZIa2tNYjlrV0FVYUE3dFFZWHBZMmFQTTF3CmxDWEVoMXQ4NFlET1JTb2FKUlhW
            K24rYy9kYkFCRVRCQ1BSMEFLNnB0NzQKLS0tIDVPWnFySFg4VzVQWDI1YlptRzFx
            WUU2ekloMjdtRTVLcHFia3ZDdGE5MUEKv0sjNQkF5uL8IYYd5ZADZLgD0HFNpwDo
            Y95KfSeeHwI2NwWI8rCPvNG7JdJS3gKYWe2t20gKN+tl2eCRVXzCYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:55:43Z"
    mac: ENC[AES256_GCM,data:EiHnw81I1LWssjurB7S9OIZx5x9CtpeW3eY+MkQ034RpEh9Y3Hq5zBQsVVMDshV2Xasn5VwmCNYSeRlLjXMusuQWPCoJS7LqGPWUqemxGGoF/zeHx980OJXvARcGWegUzSInXPeBIdLQC1Ys1De1K4dFgLvvSMjoEtZwDpkFgdc=,iv:zGtQ33e6NJqfC4QJ7fSea19vbA4Q/f+rOcF6DoNJIKw=,tag:/xXS328A4qruQfs/xNrzfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
